// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fairTeams.Core;

namespace fairTeams.Core.Migrations
{
    [DbContext(typeof(MatchRepository))]
    [Migration("20201227174352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("fairTeams.Core.Demo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Demo");
                });

            modelBuilder.Entity("fairTeams.Core.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CTScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Map")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("fairTeams.Core.Match", b =>
                {
                    b.HasOne("fairTeams.Core.Demo", "Demo")
                        .WithMany()
                        .HasForeignKey("DemoId");

                    b.Navigation("Demo");
                });
#pragma warning restore 612, 618
        }
    }
}
