// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fairTeams.Core;

namespace fairTeams.API.Migrations.MatchRepository
{
    [DbContext(typeof(fairTeams.Core.MatchRepository))]
    [Migration("20210926220103_AddMatchType")]
    partial class AddMatchType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("fairTeams.Core.Demo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GameRequestMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameRequestMatchId");

                    b.ToTable("Demo");
                });

            modelBuilder.Entity("fairTeams.Core.GameRequest", b =>
                {
                    b.Property<ulong>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OutcomeId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Token")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.ToTable("GameRequest");
                });

            modelBuilder.Entity("fairTeams.Core.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CTScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Map")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("fairTeams.Core.MatchStatistics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiveKill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourKill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialSide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OneKill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SteamID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreeKill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TwoKill")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("fairTeams.Core.Demo", b =>
                {
                    b.HasOne("fairTeams.Core.GameRequest", "GameRequest")
                        .WithMany()
                        .HasForeignKey("GameRequestMatchId");

                    b.Navigation("GameRequest");
                });

            modelBuilder.Entity("fairTeams.Core.Match", b =>
                {
                    b.HasOne("fairTeams.Core.Demo", "Demo")
                        .WithMany()
                        .HasForeignKey("DemoId");

                    b.Navigation("Demo");
                });

            modelBuilder.Entity("fairTeams.Core.MatchStatistics", b =>
                {
                    b.HasOne("fairTeams.Core.Match", null)
                        .WithMany("PlayerResults")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("fairTeams.Core.Match", b =>
                {
                    b.Navigation("PlayerResults");
                });
#pragma warning restore 612, 618
        }
    }
}
