// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fairTeams.DemoHandling;

namespace fairTeams.API.Migrations.ShareCodeRepository
{
    [DbContext(typeof(fairTeams.DemoHandling.ShareCodeRepository))]
    partial class ShareCodeRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("fairTeams.DemoHandling.ShareCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EarliestRetry")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("ShareCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
