// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace fairTeams.API.Migrations.SteamUserRepository
{
    [DbContext(typeof(fairTeams.DemoHandling.SteamUserRepository))]
    [Migration("20210116000930_AddRank")]
    partial class AddRank
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("fairTeams.DemoHandling.MatchMakingSteamUser", b =>
                {
                    b.Property<long>("SteamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthenticationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSharingCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamID");

                    b.ToTable("SteamUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
