name: backend ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - name: build debug
        run: dotnet build --configuration Debug
        working-directory: backend
      - name: build release
        run: dotnet build --configuration Release
      - name: upload debug build artifacts
        uses: actions/upload-artifact@main
        with:
          name: backend
          path: backend/bin/Debug
      - name: upload release build artifacts
        uses: actions/upload-artifact@main
        with:
          name: backend
          path: backend/bin/Release
