name: backend ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - run: dotnet build
        working-directory: backend
      - name: upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: backend
          path: backend/bin
