name: backend ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - name: build
        run: dotnet build --configuration Release
        working-directory: backend
      - name: publish
        run: dotnet publish --configuration Release -r linux-x64 --self-contained false
        working-directory: backend
      - name: upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: backend-release
          path: backend/bin/Release/net5.0/publish
