name: continuous deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
        working-directory: frontend
      - run: flutter build web
        working-directory: frontend
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: frontend/build/web
      - name: Display structure of build files
        run: ls -R
        working-directory: frontend/build/web
      - uses: erickzanardo/flutter-gh-pages@v2
        with:
          workingDir: frontend
